"""edited return

Revision ID: 4e14eddfcf02
Revises: 90bba088fdce
Create Date: 2022-07-06 16:21:41.526605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e14eddfcf02'
down_revision = '90bba088fdce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
