"""edited return

Revision ID: d1a76f69ca29
Revises: 4e14eddfcf02
Create Date: 2022-07-06 16:24:57.837435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a76f69ca29'
down_revision = '4e14eddfcf02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
